version: "3"
services:
  admin-db:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_DATABASE: admin
    ports:
      - 27017:27017
    volumes:
      - admin-db:/data/db
    networks:
      admin-backend-network:

  admin-app:
    build: "./"
    environment:
      SECRET_JWT: "sadkfiek"
      PORT: 3001
      MONGO_DEV: "mongodb://admin-db:27017/admin"
    ports:
      - "7500:3001"
    depends_on:
      - admin-db
    networks:
      admin-backend-network:

networks:
  admin-backend-network:

volumes:
  admin-db:
